---
# tasks file for dovry.htpc-programs

- name: programs - Include programs.yml
  ansible.builtin.import_tasks: programs.yml

- name: programs - Include docker.yml
  when: docker is defined
  ansible.builtin.import_tasks: docker.yml  # 

- name: programs - Include snapraid.yml
  when: snapraid is defined
  ansible.builtin.import_tasks: snapraid.yml  # 
    
- name: programs - Include samba.yml
  when: samba is defined
  ansible.builtin.import_tasks: samba.yml  # 
  tags:
    - samba
    
- name: programs - Include nfs.yml
  when: nfs is defined
  ansible.builtin.import_tasks: nfs.yml  # 