---
# tasks/snapraid.yml file for dovry.htpc-programs

- name: programs > snapraid - include vars/snapraid_vars.yml
  include_vars: snapraid_vars.yml

- name: programs > snapraid - template config file
  template:
    src: files/snapraid.conf.j2
    dest: "{{ snap_conf }}"
    owner: root
    group: root
    mode: "644"
  # initiate sync in the background while the rest of the tasks run
  notify: programs > snapraid - run snapraid sync

- name: programs > snapraid - fetch snapraid-runner
  get_url:
    url: "https://raw.githubusercontent.com/Chronial/snapraid-runner/master/snapraid-runner.py"
    dest: "{{ snap_runner_py }}"
    owner: root
    group: root
    mode: 644

- name: programs > snapraid - template runner
  template:
    src: files/snapraid-runner.j2
    dest: "{{ snap_runner_conf }}"

- name: programs > snapraid - setup cronjob for snapraid sync
  cron:
    name: "snapraid-runner.py sync job"
    minute: "{{ snap_minute }}"
    hour: "{{ snap_hour }}"
    day: "{{ snap_day }}"
    snap_weekday: "*"
    snap_month: "*"
    job: "python3 {{ snap_runner_py }} -c {{ snap_runner_conf }}"

- name: programs > snapraid - check on sync job
  async_status:
    jid: "{{ sync_sleep.ansible_job_id }}"
  register: sync_result
  until: sync_result.finished
  retries: 30