---
# playbook to install the software from roles/*
# ansible-playbook install.yml

- hosts: htpc
  become: true
  vars_files: 
    - ~/.ansible/vault
  tasks:

  - name: bootstrap
    ansible.builtin.import_role:
      name: dovry.htpc-bootstrap # prepare the system

  - name: programs
    ansible.builtin.import_role:
      name: dovry.htpc-programs # prepare the system
      
  - name: docker-compose
    ansible.builtin.import_role:
      name: dovry.htpc-docker-compose # prepare the system

