---
# playbook to install the software from roles/*
# ansible-playbook install.yml

- hosts: htpc
  become: true
  tasks:
    #- dovry.htpc-bootstrap # prepare the system
  - name: bootstrap the system
    ansible.builtin.import_role: 
      name: dovry.htpc-bootstrap
  #  - dovry.htpc-programs  # install required software
  #  - dovry.htpc-docker-compose # setup HTPC containers
