---
# playbook to install the software from roles/*
# ansible-playbook install.yml

- hosts: htpc
  become: yes
  vars_files: 
    - ~/.ansible/vault
  tasks:

  - name: main - verify become password
    when: ansible_become_pass
    ansible.builtin.debug: 
      msg: become pass is defined #, is "{{ ansible_become_pass }}"
    tags:
      - vars_check

  - name: docker-compose - verify docker user
    when: ansible_user
    ansible.builtin.debug:
      msg: ansible user is defined #, is "{{ ansible_user }}"
    tags:
      - vars_check


  - name: programs
    ansible.builtin.import_role:
      name: dovry.htpc-programs # prepare the system
    tags:
      - samba

  - name: bootstrap
    ansible.builtin.import_role:
      name: dovry.htpc-bootstrap # prepare the system

  - name: docker-compose
    ansible.builtin.import_role:
      name: dovry.htpc-docker-compose # prepare the system