---
# defaults file for dovry.htpc-programs

docker: true
snapraid: true
samba: true
nfs: true

apt_arch: amd64

# DOCKER
docker_apt_repository: "deb [arch={{ apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
docker_apt_ignore_key_error: true
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

qol_pkgs: true # general usability, vim, tree, etc.

snap_conf: /etc/snapraid.conf

snap_minute: "0" # XX:00 
snap_hour: "4" # 04:XX AM
snap_day: "1-31/2" # every other day
snap_weekday: "*"
snap_month: "*"

delete_threshold: 250
snap_email_subject: "[SnapRAID] Status Report"
snap_mail_port: ""

samba_service_enabled: enabled
samba_service_state: restarted

# nfs share rw | ro -- read/write or read only
nfs_rx: ro