---
# defaults file for dovry.htpc-programs

apt_arch: amd64

# DOCKER
docker_apt_repository: "deb [arch={{ apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
docker_apt_ignore_key_error: true
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg