---
# handlers file for dovry.htpc-programs

- name: programs > snapraid - run snapraid sync
  command: "snapraid sync"
  async: 1000
  poll: 0
  register: sync_sleep

- name: programs > samba - restart samba service
  service:
    name: smdb
    enabled: "{{ samba_service_enabled }}"
    state: "{{ samba_service_state }}"

- name: programs > nfs - initialize exportfs
  command: "exportfs -ra"

- name: programs > nfs - restart nfs-kernel-server
  service:
    name: nfs-kernel-server
    state: restarted