---
# tasks file for dovry.htpc-docker

- name: docker - Remove older Docker version
  apt:
    state: absent
    name:
      - docker-ce
      - docker-compose
      - docker.io

- name: docker - Install dependencies
  apt:
    state: present
    update_cache: true
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - gnupg2

- name: docker - Add Docker apt key.
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: docker - install docker packages
  apt:
    state: present
    update_cache: true
    name:
      - docker-ce
      - docker-compose
  notify: docker - restart docker service

- name: docker - add users to docker group
  include_tasks: docker-users.yml
  when: docker_users