---
# vars/snapraid_vars.yml for dovry.htpc-programs

snap_conf: /etc/snapraid.conf # has default

snap_runner_py: /opt/snapraid/snapraid-runner.py
snap_runner_conf: /opt/snapraid/snapraid-runner.conf

# CRON - all values have a default
snap_minute: "0"
snap_hour: "4"
snap_day: "*"
snap_weekday: "*"
snap_month: "*"

# leave empty to disable
snap_log: snapraid.log
snap_log_size_in_kb: 2000 # this is KiB, 10.000 is 10MB logfile

# comma seperated
mail_send_on: error # success,error

# abort operation if there are more deletes than this, set to -1 to disable
delete_threshold:  # default is 250 files

# true = summary || false = full output
snap_short_mail: true
# title of email report
snap_mail_subject: # has default

# mail sender
snap_mail_user:
# mail sender pass
# if you're using gmail, create an app password https://tinyurl.com/yb8cbr2p
snap_mail_pass: 


# if another address should recieve the mail instead of snap_mail_user
snap_mail_recipient:

# SMTP
snap_mail_host: smtp.gmail.com
snap_mail_port: 465
snap_mail_ssl: true 

# scrub
snap_scrub: enabled
snap_scrub_percent: 22
snap_scrub_older_than: 12
