---
# vars/snapraid_vars.yml for dovry.htpc-programs

snap_conf: /etc/snapraid.conf # has default

# CRON
snap_runner_py: /opt/snapraid/snapraid-runner.py
snap_runner_conf: /opt/snapraid/snapraid-runner.conf

# leave empty to disable
snap_log: snapraid.log
snap_log_size_in_kb: 10000 # this is KiB, 10.000 is 10MB logfile

# comma seperated
mail_send_on: "error" # success,error

# abort operation if there are more deletes than this, set to -1 to disable
delete_threshold:  # has default

# true = summary || false = full output
snap_short_mail: true
# title of email report
snap_mail_subject: "" # has default

# mail sender
snap_mail_user:
# mail sender pass
snap_mail_pass:

# if another address should recieve the mail instead of snap_mail_user
snap_mail_recipient:

# SMTP
snap_mail_host: smtp.gmail.com
snap_mail_port: "465" # has default
snap_mail_ssl: true 

# scrub
snap_scrub: enabled
snap_scrub_percent: 22
snap_scrub_older_than: 12
